services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
