name: "Build and Publish"
description: Builds and optionally publishes the package
inputs:
  package:
    description: "The package to build and publish"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: pnpm --filter $PACKAGE install
      env:
        PACKAGE: ${{ inputs.package }}
    - name: Build
      shell: bash
      run: pnpm --filter $PACKAGE build
      env:
        PACKAGE: ${{ inputs.package }}
    - name: Version
      shell: bash
      run: |
        pnpm --filter $PACKAGE exec pnpm version ${{ needs.version.outputs.version }} --no-git-tag-version
      env:
        PACKAGE: ${{ inputs.package }}
    - name: Add environment variable with NPM token to .npmrc
      shell: bash
      run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
    - name: Publish
      shell: bash
      run: |
        pnpm --filter $PACKAGE publish --access=public --no-git-checks
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        PACKAGE: ${{ inputs.package }}
