name: Build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release:
        description: "Create a release"
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: 22

jobs:
  version:
    name: "Generate version"
    uses: ./.github/workflows/version.yml
    with:
      release: ${{ github.event.inputs.release }}

  cms-plugin-build-publish:
    name: "cms-plugin: Build and Publish"
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build and Publish
        uses: ./.github/actions/build-publish
        with:
          package: "cms-plugin"

  common-build-publish:
    name: "common: Build and Publish"
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build and Publish
        uses: ./.github/actions/build-publish
        with:
          package: "common"

  releaser-build-publish:
    name: "releaser: Build and Publish"
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build and Publish
        uses: ./.github/actions/build-publish
        with:
          package: "releaser"

  cms-example-build-publish:
    name: "cms-example: Build and Publish"
    runs-on: ubuntu-latest
    needs: [version, cms-plugin-build-publish]
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build and Publish
        uses: ./.github/actions/build-publish
        with:
          package: "cms-example"
