name: Build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release:
        description: "Create a release"
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: 22

jobs:
  version:
    name: "Generate version"
    uses: ./.github/workflows/version.yml
    with:
      release: ${{ github.event.inputs.release }}

  cms-plugin-build-publish:
    name: "cms-plugin: Build and Publish"
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build and Publish
        uses: ./.github/actions/build-publish
        with:
          package: "cms-plugin"
          version: ${{ needs.version.outputs.version }}
          npmToken: ${{ secrets.NPM_TOKEN }}
      - name: Upload cms-plugin 'dist' directory
        uses: actions/upload-artifact@v4
        with:
          name: cms-plugin-dist
          path: libs/cms-plugin/dist

  common-build-publish:
    name: "common: Build and Publish"
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build and Publish
        uses: ./.github/actions/build-publish
        with:
          package: "common"
          version: ${{ needs.version.outputs.version }}
          npmToken: ${{ secrets.NPM_TOKEN }}

  releaser-build-publish:
    name: "releaser: Build and Publish"
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build and Publish
        uses: ./.github/actions/build-publish
        with:
          package: "releaser"
          version: ${{ needs.version.outputs.version }}
          npmToken: ${{ secrets.NPM_TOKEN }}

  cms-example-build:
    name: "cms-example: Build"
    runs-on: ubuntu-latest
    needs: [version, cms-plugin-build-publish]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Download cms-plugin 'dist' directory
        uses: actions/download-artifact@v4
        with:
          name: cms-plugin-dist
          path: libs/cms-plugin/dist
      - name: Build
        uses: ./.github/actions/build
        with:
          package: "cms-example"
