name: Build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release:
        description: "Create a release"
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: 22

jobs:
  version:
    name: "Generate version"
    uses: ./.github/workflows/version.yml
    with:
      release: ${{ github.event.inputs.release }}

  build-publish:
    name: "Build and Publish"
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm -r build
      - name: Version
        run: |
          pnpm -r exec pnpm version ${{ needs.version.outputs.version }} --no-git-tag-version
      - name: Add environment variable with NPM token to .npmrc
        run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
      - name: Publish
        run: |
          pnpm publish -r --access=public --no-git-checks
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
