name: Version
on:
  workflow_call:
    inputs:
      release:
        description: "Create a release"
        required: false
        default: "false"
        # using a string due to this issue with GitHub Actions: https://github.com/actions/runner/issues/1483
        type: string
    outputs:
      version:
        value: ${{ jobs.version.outputs.version }}
        description: "Version"
      version_with_sha:
        value: ${{ jobs.version.outputs.version_with_sha }}
        description: "Version with SHA"
      is_release:
        value: ${{ jobs.version.outputs.is_release }}
        description: "Is this a release?"
      is_new_release:
        value: ${{ jobs.version.outputs.is_new_release }}
        description: "Is this a new release?"
      release_version:
        value: ${{ jobs.version.outputs.release_version }}
        description: "Release version (without prerelease tag if any)"
      prerelease_tag:
        value: ${{ jobs.version.outputs.prerelease_tag }}
        description: "Prerelease tag"
      sha:
        value: ${{ jobs.version.outputs.sha }}
        description: "Commit SHA"

env:
  NODE_VERSION: 22

jobs:
  version:
    name: "Generate version"
    uses: ./.github/workflows/export.version.yml
